/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */
package pdfwordcount;

import java.io.File;
import java.io.FileWriter;
import java.io.IOException;
import java.util.ArrayList;
import javax.swing.JFileChooser;
import javax.swing.filechooser.FileFilter;

/**
 *
 * @author imran
 */
public class MainWindow extends javax.swing.JFrame {

    File statusFile;
    FileWriter statusWriter;

    /**
     * Creates new form MainWindow
     */
    public MainWindow() {
        initComponents();

        try {
            statusFile = new File("output.txt");
            if (!statusFile.exists()) {
                statusFile.createNewFile();
            }
            statusWriter = new FileWriter(statusFile);
        } catch (IOException ex) {
            ex.printStackTrace();
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jButton1 = new javax.swing.JButton();
        tfFolderLocation = new javax.swing.JTextField();
        bFileChooser = new javax.swing.JButton();
        bStart = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        taStatus = new javax.swing.JTextArea();
        bExport = new javax.swing.JButton();

        jButton1.setText("jButton1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Word Frequency Counter v1.0");

        tfFolderLocation.setText("Select a directory");

        bFileChooser.setText("...");
        bFileChooser.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bFileChooserActionPerformed(evt);
            }
        });

        bStart.setText("Start");
        bStart.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                bStartActionPerformed(evt);
            }
        });

        taStatus.setColumns(20);
        taStatus.setRows(5);
        jScrollPane1.setViewportView(taStatus);

        bExport.setText("Export");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(bExport)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(bStart, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 539, Short.MAX_VALUE)
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addComponent(tfFolderLocation)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(bFileChooser, javax.swing.GroupLayout.PREFERRED_SIZE, 57, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(tfFolderLocation, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(bFileChooser))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 254, Short.MAX_VALUE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(bStart)
                    .addComponent(bExport))
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void bFileChooserActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bFileChooserActionPerformed
        JFileChooser jfc = new JFileChooser();
        jfc.setFileFilter(new FolderFilter());
        jfc.setFileSelectionMode(JFileChooser.DIRECTORIES_ONLY);
        int showOpenDialogResponse = jfc.showOpenDialog(this);

        if (showOpenDialogResponse == JFileChooser.APPROVE_OPTION) {
            File selectedFile = jfc.getSelectedFile();
            tfFolderLocation.setText(selectedFile.getAbsolutePath());
        }

    }//GEN-LAST:event_bFileChooserActionPerformed

    private void bStartActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_bStartActionPerformed
        String directoryPath = tfFolderLocation.getText();
        final File directory = new File(directoryPath);
        if (directory.exists()) {
            new Thread(new Runnable() {
                @Override
                public void run() {
                    setStatus("Starting with '" + directory.getAbsolutePath() + "'");
                    traverseDirectory(directory);
                    setStatus("Completed\n\n");
                }
            }).start();

        } else {
            setStatus("Please select a valid Directory");
        }
    }//GEN-LAST:event_bStartActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(MainWindow.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new MainWindow().setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton bExport;
    private javax.swing.JButton bFileChooser;
    private javax.swing.JButton bStart;
    private javax.swing.JButton jButton1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea taStatus;
    private javax.swing.JTextField tfFolderLocation;
    // End of variables declaration//GEN-END:variables

    void setStatus(String text) {
        taStatus.append(text + "\n");
        printToFile(text);
    }

    void printToFile(String text) {
        if (statusWriter != null) {
            try {
                statusWriter.append(text + "\n");
            } catch (IOException ex) {
                ex.printStackTrace();
            }
        }
    }

    void traverseDirectory(File root) {
        if (root.isDirectory()) {
            File[] childs = root.listFiles();
            if (childs != null) {
                for (int i = 0; i < childs.length; i++) {
                    traverseDirectory(childs[i]);
                }
            } else {
                setStatus(root.getName() + " - Child is null");
            }

        } else {
            try {
                processFile(root);
            } catch (IOException ex) {
                setStatus("ERROR: " + " @ " + root.getAbsolutePath() + "\n" + ex.getMessage() + "\n");
            }
        }

    }

    private void processFile(File file) throws IOException {
        setStatus("Processing '" + file.getName() + "'");
        String text = Util.getText(file);
        setStatus("Total character count = " + text.length());

        ArrayList<Word> words = Util.getWordFrequencies(text);
        setStatus("Total words = " + words.size());
        for (int i = 0; i < words.size(); i++) {
            printToFile("\t" + String.format("%6d", words.get(i).count) + "\t" + words.get(i).text);
        }
    }

    class FolderFilter extends FileFilter {

        @Override
        public String getDescription() {
            return "Select a directory";
        }

        @Override
        public boolean accept(File file) {
            return file.isDirectory();
        }
    }
}
